spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/project/spring/vending
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #app 실행시점에 테이블 다 지우고 다시 생성
    properties:
      hibernate:
        #        show_sql: true (print에 출력)
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hiberante.type: trace # parameter trace log로 찍어줌

